### ISSUE TITLE
Send JSON String to Frequency

### ISSUE THREAD

**Issue by larsvansoest** [derfurkan/VoiceScape#1]
Hey there,

Such a cool idea for a plugin! I saw that you send a JSON to the server every three seconds, but I suspect that will not be fast enough when dealing with split-second moments (e.g. a pk'er logs in and kills you). Perhaps you could send a message every second instead.

The events below allow you to track whenever a player enters or leaves the scope.

```java
	@Subscribe
	protected void onPlayerSpawned(final PlayerSpawned event) {
		this.client.addChatMessage(ChatMessageType.GAMEMESSAGE, "test", String.format("Player %s entered", event.getPlayer().getName()), "plugin");
	}

	@Subscribe
	protected void onPlayerDespawned (final PlayerDespawned event) {
		this.client.addChatMessage(ChatMessageType.GAMEMESSAGE, "test", String.format("Player %s left", event.getPlayer().getName()), "plugin");
	}
```
Instead of sending the entire JSON of local players at every update, you could send a JSON with only the changes of the local player scope. So, you could keep track of the players that have entered and left the scope after the last message to the server, and only send that data instead. This may reduce the JSON size, and reduces some workload for the server to process a request.

Because I was excited by the idea of this plugin, I was eager to share some ideas. Please let me know if ideas are welcome, in that case I would like to share some more!

Good luck anyways!

**Comment by derfurkan** [comment]
### **Hello thank you for being interested in the plugin.**

I set the delay to one second as you said and used the events you suggested. It now only sends a JSON message when a change is detected in the local player's environment. Other than that I have been tweaking the VoiceServer as it is my first voice chat project. I know the code is not the cleanest but I will improve it over time. I appreciate your suggestions and thank you for your time.
