### ISSUE TITLE
Could not connect to the server. Please try again later.

### ISSUE THREAD

**Issue by Jbleezy** [derfurkan/VoiceScape#4]
I get this error everytime with the plugin. There is a default public server right?

Also I'm curious to know the logistics of who can hear who. Let's say player A can see player B and player B can see player C but player A cannot see player C, what happens then?

**Comment by derfurkan** [comment]
For the first issue: The public server is "127.0.0.1" so its your localhost. This [reddit ](https://www.reddit.com/r/2007scape/comments/11fkic0/voicescape_is_finally_available_ingame_voice_chat/) post features a list with servers hosted by other people. 

And for the second issue: I don't really understand what you mean by "see". Players can only hear each other if they both are able to find the other in their surrounding. So both players need to "see" each other to be able to talk.

**Comment by Jbleezy** [comment]
I can't believe you did all this work but you didn't add a default server. The option to host your own servers is great, but there should be one unified public server that the plugin connects to automatically. I'm sure it wouldn't cost that much, and you could put a donation link in the GitHub repo and I'm sure you would easily make the money back each month.

So does having "Connect to custom server instead" unchecked do anything? Why is that even an option? Aren't there only custom servers currently?

**Comment by derfurkan** [comment]
There is a main server its bind to "127.0.0.1". In the next update this will be removed and a few features will be added.
