### ISSUE TITLE
'Could not connect to the server. Please try again later.'

### ISSUE THREAD

**Issue by touchtablet** [derfurkan/VoiceScape#6]
tried to use prox chat, and chose default everything, gave me the error message 'Could not connect to the server. Please try again later.'

**Comment by derfurkan** [comment]
The default settings are binded to the Server: "127.0.0.1" (Your localhost) Since you dont run a server on "127.0.0.1" it cannot connect to the server.
You need to connect to a Separate server hosted by you or other people.

**Comment by touchtablet** [comment]
> The default settings are binded to the Server: "127.0.0.1" (Your localhost) Since you dont run a server on "127.0.0.1" it cannot connect to the server. You need to connect to a Separate server hosted by you or other people.

is there a server that most people use? i just want to be strolling through Varrock and say hey to someone running

**Comment by derfurkan** [comment]
At the bottom of this [post ](https://www.reddit.com/r/2007scape/comments/11fkic0/voicescape_is_finally_available_ingame_voice_chat/) you can view a few servers hosted by other people.
