### ISSUE TITLE
Make it so Microphone and Speaker Selection do not show everytime on start up

### ISSUE THREAD

**Issue by Jbleezy** [derfurkan/VoiceScape#7]
This should only show the first time you install the plugin, it should then save these settings and use them everytime. Add a button to the config for users to reselect Microphone and Speaker.

**Comment by derfurkan** [comment]
Since you are not able to implement a Button in configurations i didn't thought bout that. I think i will let it be and wont change it since im not putting this much effort into it to find a workaround like side panels etc.
