### ISSUE TITLE
Cannot send voice

### ISSUE THREAD

**Issue by TheInfamousAlk** [derfurkan/VoiceScape#9]
No matter what I do I cannot send voice. Tried this on Voice Nga and thebeerkeg. Push to talk on or off, doesn't matter. And sometimes when connecting, it says "cannot open microphone". Of course, my microphone is fine, and I'm in discord talking to people right now. I am using the correct microphone and speaker in the settings.

**Comment by derfurkan** [comment]
Hey have you tried it without any app using your microphone?

**Comment by TheInfamousAlk** [comment]
I am not interested in trying it without any app using my microphone. All my other apps can use my mic while discord uses it without any issue. If this is a limitation then the plugin is not for me.
